language: node_js

sudo: false

node_js:
  - "0.10"

env:
  global:
    - PROTRACTOR_BROWSERS=firefox
    - KARMA_BROWSERS=Firefox,PhantomJS
    - KARMA_REPORTERS=spec
    # SAUCE_USERNAME
    - secure: "fMFTJzUcoNRl8RgUGgWK5VuqdBRlb8yXdQVHbS51NAFiqx03fYpOy3TJ2awfIbqAHdQ4RO1ALsxRS4KPzT40CAS9sPTcKT4qzP53ET+9wADWsfwPqH/2Hq0lgmaVtGeEJjydf47p3aKClA9BLTpYmQxVA3zJBaRU/6mHLi7611k="
    # SAUCE_ACCESS_KEY
    - secure: "evBwL+vPJmYsQT5+Ov/REic9pZ3XLGNCidmm03aeE//Ibpc7Cl+WsgfBO+aZvZNoEbdGovPdZh/zGWSIvKecWpgaHL+Qcq7uxaVqK98+FHEykWvliyZ4flZ01Eubnwi2ytNkNFKm+UiLgEDJ2hIoAjfLGa2eTAlpO89VDN1PxyY="


install:
  - npm install
  - cd sample_project
  - ../node_modules/.bin/bower install
  - cd ..

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - USE_SAUCELABS=0 grunt test
  - cd sample_project && ../node_modules/.bin/grunt test:e2e --no-coverage --browsers="chrome,firefox,internet explorer,safari,opera"

addons:
  sauce_connect: true
